# This is a basic workflow to help you get started with Actions

name: Terraform demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.6.0
        with:
          terraform_version: 1.5.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_AD_CLIENT_ID}}
          client-secret: ${{secrets.AZURE_AD_CLIENT_SECRET}}
          tenant-id: ${{secrets.AZURE_AD_TENANT_ID}}

      - name: Terraform Init
        uses: terraform init

      - name: Terraform Validate
        uses: terraform validate

      - name: Terraform Plan
        uses: terraform plan -out=tfplan


    
